version: '3'

networks:
  loki:

services:
  loki:
    container_name: loki-container
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    volumes:
      - ./config:/etc/loki/
    command: -config.file=/etc/loki/loki-config.yaml -log.level=debug
    networks:
      - loki

  promtail:
    container_name: promtail-container
    image: grafana/promtail:2.4.0
    volumes:
      - ./storage/logs:/logs
      - ./config:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml -log.level=debug
    networks:
      - loki